<?php

namespace AppBundle\Repository;

/**
 * todoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class todoRepository extends \Doctrine\ORM\EntityRepository
{
}
